version: "3.7"

services: 
  postgres_db:
    image: postgres:13.4
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_EXTENSION="uuid-ossp"
    ports: 
      - 5432:5432
    volumes: 
      - postgres-data:/var/lib/postgresql/data/
      - ./docker/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql

volumes: 
  postgres-data:
